print("Vamos começar algumas operações matemáticas!")
print("---------------------------------------------------------------")
print("Vamos começar com a soma!")
num1 = int(input("Digite o primeiro numero para soma: "))
num2 = int(input("Digite o segundo numero para soma: "))
res1 = (num1 + num2)
print("o resultado é: ",res1)
print("---------------------------------------------------------------")
print("Agora vamos para subtração!")
num3 = int(input("Digite o primeiro numero: "))
num4 = int(input("Digite o segundo numero: "))
res2 = (num3-num4)
print("O resultado é: ",res2)
print ("--------------------------------------------------------------")
print(" Agora vamos para a multiplicação!!")
num5 = int(input("Digite o primeiro numero: "))
num6 = int(input("Digite o segundo numero: "))
res3 = (num5 * num6)
print("O resultado é: ")
print("----------------------------------------------------------------")
print("Vamos para divisao!")
num7 = int(input("Digite o primeiro numero: "))
num8 = int(input("Digite o segundo numero: "))
res4 = (num7 / num8)
print("O resultado é: ",res4)
print("----------------------------------------------------------------")
print(" Vamos para o resto de divisão!")
num9 = int(input(" Digite o primeiro numero: "))
num10 = int(input(" Digite o segundo numero: "))
res5 = (num9 % num10)
print("O resultado é: ",res5)
print("----------------------------------------------------------------")
print("Vamos para potenciação!")
num11 = int(input("Digite o numero da base: "))
num12 = int(input("Digite qual sera a potência para base informada: "))
res6 = (num11 ** num12)
print("O resultado é: ",res6)
print("----------------------------------------------------------------")
print("Agora vamos calcular a média de 3 numeros!")
num13 = int(input("Digite o seu primeiro numero: "))
num14 = int(input("Digite o seu segundo numero: "))
num15 = int(input("Digite o seu terceiro numero: "))
res7 = (num13 + num14 + num15)/3
print("O resultado é: ",res7)
print("----------------------------------------------------------------")
print("Vamos converter a temperatura em C para F!")
num16 = float(input(" Digite a sua temperatura em graus Celsius: "))
res8 = num16 *(9/5) + 32
print(" O resultado da sua temperatura é: ",res8)
print("----------------------------------------------------------------")
print("Agora vamos converter dolar em real !")
dolar = float(input("Informe a quantidade de dólar para conversão: US$ "))
cotacao = float(input ("Informe o valor da cotação do dólar: R$ "))
conversao = dolar*cotacao
print("A quantidade de dólar convertido em real é: R$",conversao)
print("-----------------------------------------------------------------")
print("Vamos agora calcular a área de um retangulo!")
altura = int(input("Informe a altura do seu retangulo: "))
largura = int(input("Informe a largura do seu retangulo: "))
area = altura * largura
print("A área do seu retangulo é: ",area)
print("-----------------------------------------------------------------")
